### ISSUE TITLE
Is this the latest replacement of librk_aiq

### ISSUE THREAD

**Issue by idreamerhx** [rockchip-linux/camera_engine_cifisp#1]
Recently I'm testing rkisp1 (driver, gstreamer-extra, rkcamsrc). There may be too old for librk_aiq.so in gstreamer-rockchip-extra when parsing tuning xml. And some exception raise:

#4  0x0000007f9c6d7130 in memcpy () at /usr/lib/libc.so.6
#5  0x0000007f9c170554 in CamCalibDbAddAwbGlobal (hCamCalibDb=0x558535c220, pAddAwbGlobal=0x7fc360e218) at source/cam_calibdb_api.c:1855
#6  0x0000007f9c15ed98 in CalibDb::parseEntryAwbGlobals(tinyxml2::XMLElement const*, void*) (this=0x558540cfc0, pelement=0x5585315e68, param=0x0)
#7  0x0000007f9c1568fc in CalibDb::parseEntryCell(tinyxml2::XMLElement const*, int, bool (CalibDb::*)(tinyxml2::XMLElement const*, void*), void*) (this=0x558540cfc0, pelement=0x5585315e00, noElements=2, func=
#8  0x0000007f9c15bee0 in CalibDb::parseEntryAwb(tinyxml2::XMLElement const*, void*) (this=0x558540cfc0, pelement=0x5585315d98, param=0x0) at calibdb.cpp:2113
#9  0x0000007f9c157c54 in CalibDb::parseEntrySensor(tinyxml2::XMLElement const*, void*) (this=0x558540cfc0, pelement=0x5585315d30, param=0x0)
#10 0x0000007f9c156608 in CalibDb::CreateCalibDb(char const*) (this=0x558540cfc0, device=0x55853eea30 "/etc/cam_iq/OV13850.xml") at calibdb.cpp:1043
#11 0x0000007f9c12b008 in CamIA10Engine::initStatic(char*) ()
#12 0x0000007f9c12a2d8 in rk_aiq_init () at /usr/local/lib/librk_aiq.so
#13 0x0000007f9c344828 in rkisp1_3a_core_init (rkisp1_core=0x558540c000, params=params@entry=0x7fc360ed50) at rkcamsrc/rkisp1/v4l2.c:221
#14 0x0000007f9c344280 in RKISP1_3A_THREAD_CREATE (params=params@entry=0x7fc360ed50) at rkcamsrc/rkisp1/thread.c:47
#15 0x0000007f9c3437dc in gst_rkcamsrc_start (src=<optimized out>)

I found libcam_engine_cifisp.so provides nearly the same symbols like  librk_aiq.
I got some errors on rk3399 running dumpsys:
CAMHALInfo:   dumpsys start !

CAMHALError:  :no camera connected!!
CAMHALError:  p:no camera connected to isp !!
CAMHALInfo:   construct ISP dev........
CAMHALInfo:   init ISP dev......
Segmentation fault (core dumped)

The camera (ov13850) is ok to capture nearly black images without 3A.

**Comment by idreamerhx** [comment]
the tuning xml (OV13850.xml) is from firefly rk3399 android 7.1

**Comment by idreamerhx** [comment]
ov13850 works. commit: If4f376960a222a2b5c14602f0c36b4abc53718f2.  thanks!
